apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artemis-federated-data
  labels:
    app: artemis-federated
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi